#!/bin/bash
# Quick fix for missing token IDs
# This script will help you add token IDs to .env

echo "🔧 Quick Fix: Missing Token IDs"
echo ""
echo "You need to add POLYMARKET_TOKEN_UP_ID and POLYMARKET_TOKEN_DOWN_ID to your .env file"
echo ""
echo "📋 Steps:"
echo "1. Get token IDs from Polymarket:"
echo "   - Go to https://polymarket.com"
echo "   - Navigate to a 'Bitcoin Up/Down 15m' market"
echo "   - Open DevTools (F12) → Network → WS"
echo "   - Click on WebSocket to ws-subscriptions-clob.polymarket.com"
echo "   - Click 'Messages' tab"
echo "   - Look for messages with 'asset_id' fields"
echo "   - Copy TWO different asset_id values"
echo ""
echo "2. Add to .env file:"
echo "   cd $(dirname "$0")"
echo "   nano .env"
echo "   # Add these lines:"
echo "   POLYMARKET_TOKEN_UP_ID=your_up_token_id"
echo "   POLYMARKET_TOKEN_DOWN_ID=your_down_token_id"
echo ""
echo "3. Or use the helper script:"
echo "   bash add_token_ids_to_env.sh UP_TOKEN_ID DOWN_TOKEN_ID"
echo ""
echo "📚 See FIX_MISSING_TOKEN_IDS.md for detailed instructions"
